win32 libs from False.Genesis.
"Forget about 2-win32libs.patch, here's a zip with the .lib files. :)
(Googlemail didn't let me send it as an actual .zip for stupid reasons -
just rename it)

The SDLmain.lib is a custom build with HAVE_ALLOCA disabled because it
caused linker errors when trying to link Aquaria.exe against it.
("undefined reference to _alloca_probe_16" and some more)

Linking with mingw works fine now, and using -O2 instead of -O3 in
release mode even fixed instant crashing when loading some maps
(probably yet another compiler optimization problem of mingw/gcc 4.6.0)"